### ISSUE TITLE
Bulk download link on Discord unavailable.

### ISSUE THREAD

**Issue by vlachvojta** [Xmader/musescore-dataset#6]
Current new option for bulk download is mentioned on Discord: 
https://discord.com/channels/774491656643674122/777457743983411221/1032054445422420039

(You must join the [LibreScore Community Discord](https://discord.gg/DKu7cUZ4XQ) first to see the message.)  
[![Discord](https://img.shields.io/discord/774491656643674122?color=7289da&label=Discord&logo=discord)](https://discord.gg/DKu7cUZ4XQ)

Or directly from here
https://github.com/musescore/MuseScore/tree/30557dec4e573f0aa5e78043da1b7564da222452

I don't really know any background of the commit, but commit message "fire us" seems sus to me...

**Comment by Xmader** [comment]
Thanks, the link in the README has been updated.
